import Anthropic from "@anthropic-ai/sdk";
import { profileToPromptText } from "../profile.js";

/**
 * Generates weekly briefing content using Claude.
 */
export class BriefingGenerator {
  constructor(config, logger) {
    this.config = config;
    this.log = logger.child({ module: "briefing-generator" });
    this.client = new Anthropic({ apiKey: config.anthropicApiKey });
    this.model = config.claudeModel;
  }

  /**
   * Generate a briefing from scored calls.
   * @param {object[]} calls - Scored call rows from the database
   * @returns {Promise<{subject: string, bodyHtml: string, bodyText: string}>}
   */
  async generate(calls) {
    if (calls.length === 0) {
      return this._emptyBriefing();
    }

    const today = new Date().toISOString().split("T")[0];
    const callSummaries = calls
      .map(
        (c, i) =>
          `${i + 1}. [Score: ${(c.relevance_score * 100).toFixed(0)}%] ${c.title}
   Programme: ${c.programme || "N/A"} | Deadline: ${c.deadline_date || "TBD"}
   Role: ${c.suggested_role} | Budget: ${c.budget || "N/A"}
   URL: ${c.url}
   Reasoning: ${c.reasoning}
   Action: ${c.action_items}
   Risks: ${c.risk_flags}`
      )
      .join("\n\n");

    const prompt = `You are a funding advisor for an NGO. Generate a professional weekly briefing email about new EU funding opportunities.

ORGANIZATION CONTEXT:
${profileToPromptText()}

TODAY'S DATE: ${today}

SCORED CALLS (sorted by relevance):
${callSummaries}

Generate a briefing with:
1. A concise subject line
2. An executive summary (2-3 sentences)
3. TOP OPPORTUNITIES section with the highest-scoring calls (score >= 60%), each with:
   - Title, programme, deadline
   - Why it's relevant (1 sentence)
   - Recommended action and role
4. WORTH MONITORING section for moderate matches (40-59%)
5. UPCOMING DEADLINES as a quick-reference table
6. Brief closing with recommended next steps

Output as JSON with three fields:
{
  "subject": "...",
  "bodyText": "... (plain text version)",
  "bodyHtml": "... (HTML email version with inline styles, professional formatting)"
}

Make it actionable and specific. Use Romanian organizational context but write in English.`;

    try {
      const response = await this.client.messages.create({
        model: this.model,
        max_tokens: 4096,
        messages: [{ role: "user", content: prompt }],
      });

      const text = response.content[0]?.text || "";
      const jsonMatch = text.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        this.log.warn("No JSON found in briefing response");
        return this._fallbackBriefing(calls, today);
      }

      const parsed = JSON.parse(jsonMatch[0]);
      return {
        subject: parsed.subject || `EU Funding Briefing — ${today}`,
        bodyHtml: parsed.bodyHtml || parsed.bodyText || "",
        bodyText: parsed.bodyText || "",
      };
    } catch (err) {
      this.log.error({ err: err.message }, "Failed to generate briefing with Claude");
      return this._fallbackBriefing(calls, today);
    }
  }

  _emptyBriefing() {
    const today = new Date().toISOString().split("T")[0];
    return {
      subject: `EU Funding Briefing — ${today} — No New Opportunities`,
      bodyText: "No new relevant EU funding calls were found this week. The scanner will continue monitoring all portals.",
      bodyHtml: `<html><body style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px">
        <h1 style="color:#003399">EU Funding Weekly Briefing</h1>
        <p>No new relevant EU funding calls were found this week.</p>
        <p>The scanner will continue monitoring all portals.</p>
        <hr><p style="color:#666;font-size:12px">Generated by AMPE EU Call Scanner</p>
      </body></html>`,
    };
  }

  _fallbackBriefing(calls, today) {
    const topCalls = calls.filter((c) => c.relevance_score >= 0.6);
    const modCalls = calls.filter((c) => c.relevance_score >= 0.4 && c.relevance_score < 0.6);

    const lines = [`EU Funding Weekly Briefing — ${today}`, "", `Found ${calls.length} relevant calls.`, ""];

    if (topCalls.length > 0) {
      lines.push("=== TOP OPPORTUNITIES ===", "");
      for (const c of topCalls) {
        lines.push(`- [${(c.relevance_score * 100).toFixed(0)}%] ${c.title}`);
        lines.push(`  Programme: ${c.programme} | Deadline: ${c.deadline_date || "TBD"}`);
        lines.push(`  ${c.url}`, "");
      }
    }

    if (modCalls.length > 0) {
      lines.push("=== WORTH MONITORING ===", "");
      for (const c of modCalls) {
        lines.push(`- [${(c.relevance_score * 100).toFixed(0)}%] ${c.title}`);
        lines.push(`  ${c.url}`, "");
      }
    }

    const bodyText = lines.join("\n");
    return {
      subject: `EU Funding Briefing — ${today} — ${topCalls.length} Top Opportunities`,
      bodyText,
      bodyHtml: `<html><body style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px"><pre>${bodyText}</pre></body></html>`,
    };
  }
}
