module.exports = {
  name: 'Asociația Mereu pentru Europa (AMPE)',
  short_name: 'AMPE',
  type: 'NGO / civil society association',
  location: {
    city: 'Craiova',
    county: 'Dolj',
    region: 'South-West Oltenia',
    country: 'Romania',
    eu_member: true,
  },
  focus_areas: [
    'European integration and citizenship',
    'Youth mobility and non-formal education',
    'Adult learning and vocational training',
    'Cross-border and transnational cooperation',
    'Civil society development and capacity building',
    'Social inclusion and equal opportunities',
    'Cultural heritage and intercultural dialogue',
    'Digital transformation for civil society',
  ],
  programs_experience: [
    'Erasmus+ KA1 (Learning Mobility of Individuals)',
    'Erasmus+ KA2 (Cooperation Partnerships)',
    'Erasmus+ KA3 (Support for Policy Reform)',
    'Interreg Romania-Bulgaria (cross-border cooperation)',
    'Interreg Danube Transnational Programme',
    'ESF+ (European Social Fund Plus)',
    'Active Citizens Fund Romania (EEA Grants)',
  ],
  target_groups: [
    'Youth aged 15-30',
    'Adult learners and VET participants',
    'NGO professionals and volunteers',
    'Educators and youth workers',
    'Disadvantaged and marginalized communities',
    'Rural population in Oltenia region',
  ],
  size: 'small (under 10 staff)',
  budget_range: {
    min: 10000,
    max: 500000,
    currency: 'EUR',
    preferred_range: '30000-200000',
  },
  languages: ['Romanian', 'English'],
  partnership_experience: true,
  strengths: [
    'Strong European partner network',
    'Experienced in EU project management and reporting',
    'Non-formal education methodologies',
    'Cross-border project coordination',
    'Youth work and social inclusion programmes',
  ],
  scoring_weights: {
    thematic_relevance: 0.30,
    org_eligibility: 0.25,
    geographic_eligibility: 0.20,
    budget_fit: 0.15,
    deadline_feasibility: 0.10,
  },
};
